apiVersion: v1
entries:
  fluent-bit:
  - annotations:
      artifacthub.io/changes: |
        - add custom annotations on dashboards configmap
    apiVersion: v1
    appVersion: 1.6.10
    created: "2021-04-30T16:02:57.311537+05:30"
    description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
    digest: 57c977d5217ae3862d104a615f0a79c7a298e8261264a1f9d007de36d2fcc327
    home: https://fluentbit.io/
    icon: https://fluentbit.io/assets/img/logo1-default.png
    keywords:
    - logging
    - fluent-bit
    - fluentd
    maintainers:
    - email: eduardo@treasure-data.com
      name: edsiper
    - email: naseem@transit.app
      name: naseemkullah
    - email: towmeykaw@gmail.com
      name: Towmeykaw
    name: fluent-bit
    sources:
    - https://github.com/fluent/fluent-bit/
    urls:
    - http://localhost/charts/fluent-bit-0.12.1.tgz
    version: 0.12.1
  kube-prometheus-stack:
  - annotations:
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.43.2
    created: "2021-04-30T16:02:57.330183+05:30"
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://charts.helm.sh/stable
      version: 2.9.*
    - condition: nodeExporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 1.12.*
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 5.8.*
    description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
    digest: 23220156322f3b5d5808989b72f24184480b0415d8bab5254f85d30ace8db6dc
    home: https://github.com/prometheus-operator/kube-prometheus
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - operator
    - prometheus
    - kube-prometheus
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - name: vsliouniaev
    - name: bismarck
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    - email: scott@r6by.com
      name: scottrigby
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    name: kube-prometheus-stack
    sources:
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus
    type: application
    urls:
    - http://localhost/charts/kube-prometheus-stack-12.3.0.tgz
    version: 12.3.0
generated: "2021-04-30T16:02:57.310329+05:30"
